### ISSUE TITLE
Illumos: missing readlinkat

### ISSUE THREAD

**Issue by 0-wiz-0** [pkgconf/pkgconf#566]
After updating pkgconf in pkgsrc to 3.0.1, the [Illumos builds started failing](https://reports.pkgci.org/SmartOS/upstream/trunk/20260713T194449Z/pkgconf-3.0.1/build.log):
```
--- libpkgconf/pkg.lo ---
libpkgconf/pkg.c: In function 'pkg_get_parent_dir':
libpkgconf/pkg.c:102:31: error: implicit declaration of function 'readlinkat'; did you mean 'readlink'? [-Wimplicit-function-declaration]
  102 |                 ssize_t len = readlinkat(dirfd, targetfilename, sourcebuf, sizeof(sourcebuf) - 1);
      |                               ^~~~~~~~~~
      |                               readlink
```
In case it matters, we're still using the autoconf framework for building.

The previous pkgsrc version, 2.5.1, built fine in the same environment.

**Comment by 0-wiz-0** [comment]
[Configure output on Illumos](https://reports.pkgci.org/SmartOS/upstream/trunk/20260713T194449Z/pkgconf-3.0.1/configure.log) in case it helps.

**Comment by kaniini** [comment]
Are you using Meson?  Illumos on Meson is covered by CI, and the Autotools build system will be dropped soon.
