### ISSUE TITLE
`O_DIRECTORY` and `readlinkat` undeclared

### ISSUE THREAD

**Issue by FFY00** [pkgconf/pkgconf#389]
These symbols are only available on `_POSIX_C_SOURCE >= 200809L`.

Introduced in https://github.com/pkgconf/pkgconf/commit/e6c1d4b8bd9610444d9fb2d145610f46c881c210

---

Environment: `quay.io/pypa/manylinux2014_x86_64:2025.03.23-1`

```
      pkgconf-pypi 2.4.3-0

        Subprojects
          pkgconf     : YES 1 warnings

        User defined options
          Native files: /project/.mesonpy-7_j9lmot/meson-python-native-file.ini
          b_ndebug    : if-release
          b_vscrt     : md
          buildtype   : release

      Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-ck7e0_8l/normal/bin/ninja
      + /tmp/pip-build-env-ck7e0_8l/normal/bin/ninja
      [1/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_audit.c.o
      [2/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_pkg.c.o
      FAILED: subprojects/pkgconf/libpkgconf.a.p/libpkgconf_pkg.c.o
      cc -Isubprojects/pkgconf/libpkgconf.a.p -Isubprojects/pkgconf -I../subprojects/pkgconf -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wimplicit-function-declaration -Wmisleading-indentation -fPIC -DLIBPKGCONF_EXPORT -DPKGCONFIG_IS_STATIC -MD -MQ subprojects/pkgconf/libpkgconf.a.p/libpkgconf_pkg.c.o -MF subprojects/pkgconf/libpkgconf.a.p/libpkgconf_pkg.c.o.d -o subprojects/pkgconf/libpkgconf.a.p/libpkgconf_pkg.c.o -c ../subprojects/pkgconf/libpkgconf/pkg.c
      ../subprojects/pkgconf/libpkgconf/pkg.c: In function ‘pkg_get_parent_dir’:
      ../subprojects/pkgconf/libpkgconf/pkg.c:101:37: error: ‘O_DIRECTORY’ undeclared (first use in this function)
        101 |   const int dirfd = open(targetdir, O_DIRECTORY);
            |                                     ^~~~~~~~~~~
      ../subprojects/pkgconf/libpkgconf/pkg.c:101:37: note: each undeclared identifier is reported only once for each function it appears in
      ../subprojects/pkgconf/libpkgconf/pkg.c:106:17: warning: implicit declaration of function ‘readlinkat’; did you mean ‘readlink’? [-Wimplicit-function-declaration]
        106 |   ssize_t len = readlinkat(dirfd, targetfilename, sourcebuf, sizeof(sourcebuf) - 1);
            |                 ^~~~~~~~~~
            |                 readlink
      [3/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_fileio.c.o
      [4/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_bsdstubs.c.o
      [5/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_buffer.c.o
      [6/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_argvsplit.c.o
      [7/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_parser.c.o
      [8/21] Compiling C object subprojects/pkgconf/pkgconf.p/cli_renderer-msvc.c.o
      [9/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_cache.c.o
      [10/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_personality.c.o
      [11/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_path.c.o
      [12/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_client.c.o
      [13/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_tuple.c.o
      [14/21] Compiling C object subprojects/pkgconf/pkgconf.p/cli_getopt_long.c.o
      [15/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_queue.c.o
      [16/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_dependency.c.o
      [17/21] Compiling C object subprojects/pkgconf/pkgconf.p/cli_main.c.o
      [18/21] Compiling C object subprojects/pkgconf/libpkgconf.a.p/libpkgconf_fragment.c.o
      ninja: build stopped: subcommand failed.
      [end of output]
```

**Comment by kaniini** [comment]
Fix merged in https://github.com/pkgconf/pkgconf/commit/664b53d5c4920e66e4a57c7515ccfd1bd1477bac

**Comment by CL-Jeremy** [comment]
Stumbled upon this while attempting to use the CMake-based workflow via `vcpkg` on macOS. Confused me quite a bit since the package manager (I use MacPorts) ships an unmodified version without issue (using just the `./configure` script). Turns out Darwin needs some special treatment as well: https://github.com/deadpixi/sam/issues/20. Submitted a PR already.
