### ISSUE TITLE
[BUG] regression from 1.8.0 -> 1.9 library output ordering

### ISSUE THREAD

**Issue by 1480c1** [pkgconf/pkgconf#268]
Hi, downstream issue https://github.com/msys2/MINGW-packages/issues/13390

For the first issue, copying relevant info here:

Previously, with 1.8.0, I got:

```bash
$ pkgconf --static --libs opusurl
-LC:/msys64/ucrt64/lib -lopusurl -lopusfile -LC:/msys64/ucrt64/lib -logg -lopus -lm -lssp -LC:/msys64/ucrt64/lib -lssl -LC:/msys64/ucrt64/lib -lws2_32 -lgdi32 -lcrypt32 -lcrypto -lws2_32 -lgdi32 -lcrypt32
```

(note the `-lssl` being after `-lopusurl`)

After MSYS2 updated to 1.9.3, I got:

```bash
$ pkgconf --static --libs opusurl
-LC:/msys64/ucrt64/lib -lssl -LC:/msys64/ucrt64/lib -lcrypto -lws2_32 -lgdi32 -lcrypt32 -lopusurl -lopusfile -LC:/msys64/ucrt64/lib -logg -lopus -lm -lssp
```

(note the position of `-lssl`)

I've narrowed that issue down to https://github.com/pkgconf/pkgconf/commit/197fcadd4c44504808a44fb257275684b5207b10, I have one that seems to work for opusurl, but not for another issue.

Second issue that is not present in the downstream issue since I just now found out about it:

with a custom compiled static gnutls and 1.8.0, I got:

```bash
$ pkgconf --static --libs gnutls
-LD:/mabs/local32/lib -lgnutls -lws2_32 -lws2_32 -lws2_32 -lgmp -latomic -ladvapi32 -lcrypt32 -lncrypt -lbcrypt -lcrypt32 -LD:/mabs/msys64/mingw32/lib -lnettle -lhogweed -lgmp -LD:/mabs/msys64/mingw32/lib -lnettle -ltasn1 -lz -lbrotlienc -LD:/mabs/msys64/mingw32/lib -lbrotlicommon -lbrotlidec -LD:/mabs/msys64/mingw32/lib -lbrotlicommon -lzstd
```

(note the duplicate `-lnettle` after `-lhogweed`)

However, with 1.9.3, I got:

```bash
$ pkgconf --static --libs gnutls
-LD:/mabs/local32/lib -lgnutls -lws2_32 -lws2_32 -lws2_32 -lgmp -latomic -ladvapi32 -lcrypt32 -lncrypt -lbcrypt -lcrypt32 -LD:/mabs/msys64/mingw32/lib -lnettle -lhogweed -lgmp -ltasn1 -lz -lbrotlienc -LD:/mabs/msys64/mingw32/lib -lbrotlicommon -lbrotlidec -lzstd
```

(notice the lack of the duplicate `-lnettle` after `-lhogweed`)

gnutls.pc lists `Requires.private: nettle, hogweed, libtasn1, zlib, libbrotlienc, libbrotlidec, libzstd`
hogweed.pc (from msys2) lists `Requires.private:  nettle`
nettle.pc (from msys2) lists `Libs: -L${libdir} -lnettle`

Somehow, the fact that hogweed depends on nettle either disappears or isn't sorted properly.

Down-downstream issue for this is https://github.com/m-ab-s/media-autobuild_suite/issues/2298#issuecomment-1266048699
link line copied here from ffmpeg's config.log
```c++
ccache g++ -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib -Wl,--nxcompat,--dynamicbase -Wl,--high-entropy-va -Wl,--as-needed -Wl,--pic-executable,-e,mainCRTStartup -Wl,--image-base,0x140000000 -ID:/mabs/local64/include -ID:/mabs/msys64/mingw64/include -LD:/mabs/local64/lib -LD:/mabs/msys64/mingw64/lib -LD:/mabs/msys64/mingw64/lib -o /tmp/ffconf.iqeyOE8l/test.exe /tmp/ffconf.iqeyOE8l/test.o -lgnutls -lws2_32 -lws2_32 -lws2_32 -lgmp -latomic -ladvapi32 -lcrypt32 -lncrypt -lbcrypt -lcrypt32 -lnettle -lhogweed -lgmp -ltasn1 -lz -lbrotlienc -lbrotlicommon -lbrotlidec -lzstd
D:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/mabs/msys64/mingw64/lib/libhogweed.a(pkcs1-sec-decrypt.o):(.text+0xa0): undefined reference to `nettle_cnd_memcpy'
```

This one seems to affect linux as well as compiling latest master (0226cdd) shows the lack of nettle after hogweed as well, despite it being present in 1.8.0. The first issue is not present on linux

**Comment by 1480c1** [comment]
If a `--debug` output is desired, I can provide them

**Comment by nikolasr** [comment]
Maybe this is also connected to https://github.com/m-ab-s/media-autobuild_suite/issues/2300 ?

**Comment by 1480c1** [comment]
Yeah, that's where I also noticed the second issue

**Comment by 1480c1** [comment]
For the second issue with gnutls, I've bisected it to 6ae17bd0efb5b52d2f51b989e14d20291c806aad as the commit causing the issue for the second nettle disappearing

**Comment by 1480c1** [comment]
I can also confirm that reverting 6ae17bd0efb5b52d2f51b989e14d20291c806aad locally brings back nettle after hogweed for gnutls

**Comment by mbpdt** [comment]
We are hitting this same issue in our static builds when upgrading to the latest version. Here is a very simple reproduction that I would like to add to the issue so the developers can more easily fix the issue. 

It consists of these three pkgconfig files:
```
File: /tmp/static/a.pc
   1   │ Name: a
   2   │ Description: a library
   3   │ Version: 1.0
   4   │ Cflags:
   5   │ Libs: -L/tmp/a/lib -l:liba-mt-x64.a
File: /tmp/static/b.pc
   1   │ includedir=/tmp/b/include
   2   │ libdir=/tmp/b/lib
   3   │
   4   │ Name: b
   5   │ Description:
   6   │ Version: 1.0
   7   │ Requires: \
   8   │   a
   9   │ Cflags: -I${includedir}
  10   │ Libs: -L${libdir} -l:libb-mt-x64.a
File: /tmp/static/c.pc
   1   │ includedir=/tmp/c/include
   2   │ libdir=/tmp/c/lib
   3   │
   4   │ Name: c
   5   │ Description:
   6   │ Version: 1.0
   7   │ Requires: \
   8   │   a \
   9   │   b
  10   │ Cflags: -I${includedir}
  11   │ Libs: -L${libdir} -l:libc-mt-x64.a
  12   │
```
and then running pkgconfig: 
```
>PKG_CONFIG_PATH=/tmp/static /opt/1.9.3/bin/pkgconf --libs c
-L/tmp/c/lib -l:libc-mt-x64.a -L/tmp/a/lib -l:liba-mt-x64.a -L/tmp/b/lib -l:libb-mt-x64.a
>PKG_CONFIG_PATH=/tmp/static /opt/1.8.0/bin/pkgconf --libs c
-L/tmp/c/lib -l:libc-mt-x64.a -L/tmp/a/lib -L/tmp/b/lib -l:libb-mt-x64.a -l:liba-mt-x64.a
```

It is immediately obvious that 1.9.3 gives a different order back, and it is clearly wrong, the liba static needs to come after both libc as well as libb.

**Comment by lazka** [comment]
@mbpdt your example now shows a different result with 1.9.4:

```
-L/tmp/c/lib -l:libc-mt-x64.a -L/tmp/b/lib -l:libb-mt-x64.a -L/tmp/a/lib -l:liba-mt-x64.a
```

bisect suggest a combination of 90b65c866bbb63fb and d9e507cc6eca95f8 are the cause for the new change.

**Comment by 1480c1** [comment]
With 1.9.4, the output of opusurl has now changed to 
```bash
$ pkgconf --static --libs opusurl
-lopusfile -lopusurl -lssl -lws2_32 -lgdi32 -lcrypt32 -lopus -lm -logg -lcrypto -lws2_32 -lgdi32 -lcrypt32
```
which will still result in broken compilations due to the ordering of opusfile and opusurl
```bash
$ gcc -static $(pkgconf --static --cflags opusurl) temp.c $(pkgconf --static --libs opusurl)
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libopusurl.a(libopusurl_la-http.o):(.text+0x3f27): undefined reference to `op_fopen'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libopusurl.a(libopusurl_la-http.o):(.text+0x5a3b): undefined reference to `op_open_callbacks'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libopusurl.a(libopusurl_la-http.o):(.text+0x5bbb): undefined reference to `op_test_callbacks
```

**Comment by wader** [comment]
Hi, i think i ran into this for https://github.com/wader/static-ffmpeg/issues/283 happy to help debug and try things

**Comment by acolwell** [comment]
I'm pretty sure this issues has to do with the qsort() call in flatten_dependency_set() (https://github.com/pkgconf/pkgconf/blob/master/libpkgconf/queue.c#L207). I believe this code is assuming that qsort() is stable, which is not guaranteed, if there are items that are considered equivalent. I tested the code below on Ubuntu Linux, Windows 10 w/ MinGW, and Windows 10 w/ Visual Studio and verified that qsort() does not preserve the original order on MinGW & Visual Studio. I believe this may be at least one cause of the library reordering problem. 

---[snip]---
#include <stdio.h>
#include <stdlib.h>

typedef struct item {
  const char* name;
  int hits;
} item_t;


static int
dep_sort_cmp(const void *a, const void *b)
{
  const item_t *itemA = *(void **) a;
  const item_t *itemB = *(void **) b;

  return itemB->hits - itemA->hits;
}

void add_item(item_t*** items, size_t* item_count, const char* name, int hits) {
  item_t* item = malloc(sizeof(item_t));
  item->name = name;
  item->hits = hits;

  if (*items == NULL) {
    *items = malloc(sizeof(item_t*));
    (*items)[0] = item;
    *item_count = 1;
    return;
  }
  if (*item_count < 1) {
    printf("Invalid item count %d\n", *item_count);
    abort();
  }

  *items = realloc(*items, (*item_count + 1) * sizeof(item_t*));
  (*items)[*item_count] = item;
  (*item_count)++;
}

void print_items(const char* label, item_t** items, size_t item_count) {
  printf("%s {", label);
  for (int i = 0; i < item_count; ++i) {
    if (i > 0) {
      printf(",");
    }
    if (items[i]) {
      printf(" (%s,%d)", items[i]->name, items[i]->hits);
    } else {
      printf(" NULL");
    }
  }
  printf(" }\n");

}

int main(int argc, const char* argv[]) {
  item_t** items = NULL;
  size_t item_count = 0;
  add_item(&items, &item_count, "itemA", 1);
  add_item(&items, &item_count, "itemB", 1);
  print_items("BEFORE", items, item_count);
  qsort(items, item_count, sizeof (void *), dep_sort_cmp);
  print_items("AFTER", items, item_count);
}
---[snip]---

**Comment by stanhu** [comment]
> I'm pretty sure this issue has to do with the qsort() call in flatten_dependency_set()

No, I tried using an insertion sort in 2e9106561a2500f39bd1ff6184b37aae2d45c71b, but it did not solve the problem.

As others have said, going to the commit before 6ae17bd0efb5b52d2f51b989e14d20291c806aad fixed the issue. Reverting that commit in `master`, however, does not fix the issue.

@kaniini Do you know what's going on here?

**Comment by kaniini** [comment]
I suspect the issue is that qsort is not guaranteed to be stable.  I did check POSIX for this, and indeed, it is not required to be stable.  It does, however, happen to be stable on Alpine.

Most likely I will incorporate musl’s smoothsort implementation in pkgconf 1.9.6 to solve this problem.

**Comment by kaniini** [comment]
Ah, actually I suspect what is happening is that the new solver is cancelling out the wrong edges in the solution when it flattens it.  I will try to get a 1.9.6 out this weekend with a fix.

**Comment by kaniini** [comment]
This should be fixed in 2.0.0

**Comment by stanhu** [comment]
FYI, I'm still seeing an issue with the library ordering. Filed https://github.com/pkgconf/pkgconf/issues/322.
